### PR TITLE
Fixed SSL

### PR DESCRIPTION
**Pull request by vikas5914**
Fixed SSL in Line no 113

### CODE REVIEW

**Review by andrewda — APPROVED** [review]

**Comment by BlackCetha** [comment]
Didn't even know that worked, thanks!

**Comment by BlackCetha** [comment]
I will release a new minor version once #12 is done.

**Comment by vikas5914** [comment]
also, composer support can be awesome.

**Comment by BlackCetha** [comment]
I personally dont use composer and have no idea how to add support for it.
If you do, please go ahead and add it.

**Comment by vikas5914** [comment]
I also don't know how to make a package for the composer, but I will learn it and make for it.

**Pull request merged**
